### ISSUE TITLE
global class with max upload rate: 30mbps does not limit yet 3mbps limits

### ISSUE THREAD

**Issue by slrslr** [cryzed/TrafficToll#13]
This does not work to limit global interface bandwidth to 30mbps upload:

$ sudo tt eno1 bwl.yaml --delay 0.5

```
...:02.888 | INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 30mbps (minimum: 1mbps) and priority: 2
...:02.888 | INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 30mbps (minimum: 1mbps) and priority: 2
...:02.941 | INFO     | traffictoll.cli:main:264 - Setting up class for: '/usr/bin/firefox' with unlimited download rate (minimum: 5mbps) and priority: 0
...:02.943 | INFO     | traffictoll.cli:main:290 - Setting up class for: '/usr/bin/firefox' with unlimited upload rate (minimum: 5mbps) and priority: 0
...:02.948 | INFO     | traffictoll.cli:main:264 - Setting up class for: 'Thunderbird' with unlimited download rate (minimum: 1mbps) and priority: 1
...:02.951 | INFO     | traffictoll.cli:main:290 - Setting up class for: 'Thunderbird' with unlimited upload rate (minimum: 1mbps) and priority: 1
...:15.401 | INFO     | traffictoll.__main__:main:19 - Aborted
...:15.401 | INFO     | traffictoll.cli:_clean_up:72 - Cleaning up QDiscs
```

But when i change line "upload: 30mbps" to "upload: 3mbps" and run same command:

$ sudo tt eno1 bwl.yaml --delay 0.5
```
...:33.002 | INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 3mbps (minimum: 1mbps) and priority: 2
...:33.002 | INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 3mbps (minimum: 1mbps) and priority: 2
...:33.051 | INFO     | traffictoll.cli:main:264 - Setting up class for: '/usr/bin/firefox' with unlimited download rate (minimum: 5mbps) and priority: 0
...:33.054 | INFO     | traffictoll.cli:main:290 - Setting up class for: '/usr/bin/firefox' with unlimited upload rate (minimum: 5mbps) and priority: 0
...:33.058 | INFO     | traffictoll.cli:main:264 - Setting up class for: 'Thunderbird' with unlimited download rate (minimum: 1mbps) and priority: 1
...:33.061 | INFO     | traffictoll.cli:main:290 - Setting up class for: 'Thunderbird' with unlimited upload rate (minimum: 1mbps) and priority: 1
...:36.674 | INFO     | traffictoll.__main__:main:19 - Aborted
...:36.675 | INFO     | traffictoll.cli:_clean_up:72 - Cleaning up QDiscs
```

then it limits the upload OK. I do not understand this.
3000kbps works though

I have installed tt using "pamac build traffictoll-git"
$ pamac info traffictoll-git
```
Name                  : traffictoll-git
Version               : 1.5.0.r1.g4569b4c-1
URL                   : https://github.com/cryzed/TrafficToll
Depends On            : python python-loguru python-psutil python-ruamel-yaml
Conflicts With        : traffictoll
Packager              : Unknown Packager
Build Date            : 16.1.2022
Install Date          : 16.1.2022
```

CONFIG file:

$ grep -v "#" bwl.yaml
```
download: 3mbps
upload: 3mbps

download-minimum: 1mbps
upload-minimum: 1mbps

processes:
  "/usr/bin/firefox":
    download-priority: 0
    upload-priority: 0
    download-minimum: 5mbps
    upload-minimum: 5mbps
    match:
      - name: "firefox"

  Thunderbird:
    download-minimum: 1mbps
    upload-minimum: 1mbps

    download-priority: 1
    upload-priority: 1
    match:
      - exe: /usr/bin/thunderbird

  JDownloader 2:
    match:
      - cmdline: .* JDownloader.jar
```

processes defined above does not utilize any significant amount of bandwidth
